# Generated by Django 2.0.4 on 2018-04-29 23:59

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobleMessage',
            new_name='MobileMessage',
        ),
        migrations.RenameModel(
            old_name='MobleNumber',
            new_name='MobileNumber',
        ),
    ]
